### ISSUE TITLE
Недоработки сайта

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#1]
1. Нет hover эффекта при наведении на кнопки. В дизайн документе он описан.

![btn](https://user-images.githubusercontent.com/75975369/109640858-08d32980-7b62-11eb-81e0-a34ae754b340.png)

**Comment by mglknFSD** [comment]
2. Тень делает заметной элемент иконки

![shadow](https://user-images.githubusercontent.com/75975369/109641084-5b144a80-7b62-11eb-9d33-9e66a026e58f.png)

**Comment by mglknFSD** [comment]
3. На странице поиска нет границ header. Границы футера нет ни на одной странице.

![header](https://user-images.githubusercontent.com/75975369/109641306-9e6eb900-7b62-11eb-8411-49434d1ed6ce.png)

**Comment by mglknFSD** [comment]
4. По best practice footer должен быть прижат к низу страницы.

![footer](https://user-images.githubusercontent.com/75975369/109641661-03c2aa00-7b63-11eb-9c7b-62870608fb15.png)

**Comment by mglknFSD** [comment]
5. Нет скруглений. 
![border-radius](https://user-images.githubusercontent.com/75975369/109641787-29e84a00-7b63-11eb-90e0-ee529820f47b.png)

**Comment by mglknFSD** [comment]
5. Доработать адаптивность сайта. 
  -  При 320px появляется горизонтальный скролл

https://user-images.githubusercontent.com/75975369/109642345-e93d0080-7b63-11eb-9b8d-0e5933791dfe.mp4

  - На некоторых разрешениях станицы выглядят не очень хорошо. 
 
Справа много пустого пространства
 
![фцащщ](https://user-images.githubusercontent.com/75975369/109642676-55b7ff80-7b64-11eb-90df-92a4ddb491a7.png)

Картинки искажаются меняя свое соотношение сторон, и одна картинка исчезает (контент для пользователя становится не доступен)

https://user-images.githubusercontent.com/75975369/109643159-e68edb00-7b64-11eb-9613-6a2fd3071937.mp4

Эти и подобные моменты нужно посмотреть и пофиксить.

**Comment by mglknFSD** [comment]
6. Ползунки слайдера немного не по центру.

![slier](https://user-images.githubusercontent.com/75975369/109643611-85b3d280-7b65-11eb-9873-022972293127.png)

**Comment by mglknFSD** [comment]
7. Эти иконки должны быть ссылками на соц сети.
![links](https://user-images.githubusercontent.com/75975369/109643940-ee02b400-7b65-11eb-9077-334dde6f4bec.png)

Меню и логотип в header-е то же.

**Comment by igorpichnenko** [comment]
Вроде исправил все пункты

**Comment by mglknFSD** [comment]
Адаптивность сайта. Проблема не решена.

При ширине 320 справа есть отступ. Форма не влезает в 320px и у нее "съедаются" паддинги (т е она не резиновая).

![responsive](https://user-images.githubusercontent.com/75975369/109925492-e44a8f00-7cd2-11eb-87c9-a1d418e850a2.jpg)
![responsive3](https://user-images.githubusercontent.com/75975369/109925494-e4e32580-7cd2-11eb-8d4d-61fd85d775ed.jpg)
![responsive2](https://user-images.githubusercontent.com/75975369/109925846-4efbca80-7cd3-11eb-8f48-30615d366e62.jpg)

При некоторых разрешениях остается вертикальный скрол.

https://user-images.githubusercontent.com/75975369/109925940-69ce3f00-7cd3-11eb-9e7b-9080b27746a2.mp4

**Comment by mglknFSD** [comment]
Адаптивность. 

Представьте, что вы с мобильного телефона, в незнакомом городе, выбираете себе гостиничный номер по вот таким фотографиям.

![images](https://user-images.githubusercontent.com/75975369/109926288-dea17900-7cd3-11eb-8db0-62fcb7c393fc.jpg)

**Comment by mglknFSD** [comment]
Иконки соц сетей после правок (черные полосы снизу)

![icons](https://user-images.githubusercontent.com/75975369/109927568-781d5a80-7cd5-11eb-9fd5-575bbdd51051.jpg)

**Comment by igorpichnenko** [comment]
Сделал карточки резиновыми до 320px, на room details если нельзя скрывать картинку и нельзя оставить, я сделал третий выриант посмотрите..
По поводу чёрточек, у вас наверное браузер лиса?) Я просто в хроме, опере и на мобиле смотрел не увидел их, но добавил text-decoration: none, сегодня установлю лису..

**Comment by mglknFSD** [comment]
Menu

1 - Иконки съехали (ниже чем на макете)
![menu](https://user-images.githubusercontent.com/75975369/110233142-28d46580-7f33-11eb-80c1-5375e7b408c2.jpg)

2 - В мобильное версии разные отступы
![menu2](https://user-images.githubusercontent.com/75975369/110233174-4e616f00-7f33-11eb-8e14-bff5bd53652e.jpg)

3 - Если "развернуть" меню в мобильное версии и перейти в десктопную будет вот такая картина.
![menu3](https://user-images.githubusercontent.com/75975369/110233201-7e107700-7f33-11eb-8a02-c1499d02df4b.jpg)

**Comment by mglknFSD** [comment]
Дата рождения, в форме регистрации, должна быть маской.

**Comment by mglknFSD** [comment]
Адаптивность.

Ширина 320. Не влезает интерфейс.
![adapt](https://user-images.githubusercontent.com/75975369/110233601-02fc9000-7f36-11eb-85be-75371225ebda.jpg)
![adapt2](https://user-images.githubusercontent.com/75975369/110233622-1f98c800-7f36-11eb-82b6-68b1affa8659.jpg)

Посмотри что бы везде все влезало.

Где 3-я картинка?
![adapt3](https://user-images.githubusercontent.com/75975369/110233633-37704c00-7f36-11eb-89e5-b08584068041.jpg)


Вертикальный скрол никуда не пропал.

https://user-images.githubusercontent.com/75975369/110233655-553db100-7f36-11eb-82d0-23a954e2cb81.mp4

**Comment by igorpichnenko** [comment]
По поводу 1 пункта, я постоянно смотрю пиксель перфект, и иконки у меня не сьехали, стоят как в макете, # @
![screenshot-82266e6c](https://user-images.githubusercontent.com/76178315/110638363-768fde80-817c-11eb-8088-bf05de0bd021.jpg)

по 2 пункту подровнял меню

по 3 на телефоне такого нет, это выходит не корректная проверка, на телефоне там страница перезагружается когда разварачиваешь меню и выбираешь компьюторную версию, могу скрины добавить

по 4 так же у меня все помещается и нет прокрутки 
![screenshot-0bebe556](https://user-images.githubusercontent.com/76178315/110638700-e1411a00-817c-11eb-80ae-1089b9927b6b.jpg)

**Comment by igorpichnenko** [comment]
Вот поидее же отрабатывает, почему на ПК не хочет в меню разработки
![Screenshot_2021-03-10-19-54-25-885_com android chrome](https://user-images.githubusercontent.com/76178315/110639964-8211f280-81da-11eb-8fe8-34b325ac7337.jpg)
![Screenshot_2021-03-10-19-54-22-402_com android chrome](https://user-images.githubusercontent.com/76178315/110640121-aa015600-81da-11eb-8dd3-8c568aeca84e.jpg)
![Screenshot_2021-03-10-19-54-15-867_com android chrome](https://user-images.githubusercontent.com/76178315/110640086-a241b180-81da-11eb-9770-d899607af6fe.jpg)

**Comment by mglknFSD** [comment]
- Картинки должны сохранять свои пропорции (не должны искажаться при различных разрешениях)
- Правые картинки у тебя наползают на левую делая ее недоступной для просмотра - все картинки при любых разрешениях должны быть видны.

https://user-images.githubusercontent.com/75975369/111041128-c950eb00-8447-11eb-81e2-297d9a2467d7.mp4

**Comment by mglknFSD** [comment]
Форма расчета стоимости не работает, нужно что бы компонент этой формы принимал значения стоимости номера, скидки и т д и производил расчет исходя из дат прибытия и отбытия.

https://user-images.githubusercontent.com/75975369/111041819-3fa31c80-844b-11eb-8f0c-3e608f8b14f2.mp4

**Comment by igorpichnenko** [comment]
Исправил фон room-details, сделал форму рабочей, вычисляет стоимость относительно количеству суток, гостей и скидки, скидку тоже корректирует, но так как информации очень мало для настоящих расчетов то реализацию сделал простую, если в поле price, discount в json room-details менять значение скидки и цены, то и расчеты все будут меняться

**Comment by mglknFSD** [comment]
Картинки должны сохранять свои пропорции (не должны искажаться при различных разрешениях)

Это не поправлено.

https://user-images.githubusercontent.com/75975369/111838146-f864d200-8909-11eb-9edf-7804d44c6816.mov

**Comment by mglknFSD** [comment]
- теперь картинки справа "съедают" картинку слева
- и меню после открытия выглядит не очень

https://user-images.githubusercontent.com/75975369/112725709-ab48b780-8f2a-11eb-9715-4976aff10b52.mp4

В моем варианте решения этой задачи это выглядело так. 

https://user-images.githubusercontent.com/75975369/112725825-32962b00-8f2b-11eb-93a0-26b355c34858.mp4

Все картинки не меняют своих пропорций и видны полностью при разных разрешениях.
Для расположения картинок я использовал гриды, хотя, думаю, можно было и на флексах сделать, но сложнее. Для относительного расположения меню использовал флексы.

**Comment by igorpichnenko** [comment]
Переделал шапку и бэграунд

**Comment by mglknFSD** [comment]
Теперь вот так это работает.

![bug](https://user-images.githubusercontent.com/75975369/113471657-7f678d80-9466-11eb-8f18-8b2b8d679160.jpg)
