### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#3]
1. vars

Именование переменных должно быть семантическим (смысловым). Обычно в дизайн системе есть главный цвет (main-color), дополнительный цвет, основной швет шрифта, цвет заголовка и т д. Что если главный цвет сменится с purple на pink, возникнет путаница. Твой вариант, крайне неудачный. Так же для шрифтов можно завести переменные.
 
![vars](https://user-images.githubusercontent.com/75975369/109660106-88b8be00-7b79-11eb-9758-04c58d58cf6e.png)

**Comment by mglknFSD** [comment]
2. reset.css я бы или установил через npm и импортировал из библиотеки или прокинул через postcss (так тоже можно), но не стал бы его копипастить в проект.

**Comment by igorpichnenko** [comment]
Добавил переменную для главного цвета и второстепенного, так же добавил переменные для шрифтов

**Comment by mglknFSD** [comment]
3. БЭМ.  Тут и везде по коду. [Именование модификаторов](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![modificator](https://user-images.githubusercontent.com/75975369/110234981-7aceb880-7f3e-11eb-98f5-92d380ef91b6.jpg)

**Comment by mglknFSD** [comment]
4. БЭМ. [Каждый компонент — отдельный блок из методологии БЭМ.](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.3)

![bem](https://user-images.githubusercontent.com/75975369/110235028-e9137b00-7f3e-11eb-85d5-b234cb12de09.jpg)

**Comment by mglknFSD** [comment]
5. Тут и в других местах. Классы с префиксом js мы использует только для поиска dom elements из javascript, стилизовать ими ничего не надо.

![js](https://user-images.githubusercontent.com/75975369/111040751-a7eeff80-8445-11eb-9e6d-9caaa81dbf3b.jpg)

**Comment by mglknFSD** [comment]
Тут есть какие-то причины не использовать css переменную?

![Screenshot 2021-03-19 at 10 51 05 PM](https://user-images.githubusercontent.com/75975369/111835218-b9348200-8905-11eb-95b5-b92171b8b7f0.png)

**Comment by mglknFSD** [comment]
Тут и в других местах необходимо группировать стили внутри селектора где это возможно. Пример для данного случая 

```css
  &__input {

    &::before {
       ...
    }

    &:checked::before {
       ...
    }

    &:checked + #{some_block}__border { // тут используется интерполяция
       ...
    }
  }
```
Удобно когда все стили для класса сгруппированы внутри этого тега и их не надо искать и сложно случайно разделить.

![Screenshot 2021-03-19 at 10 54 27 PM](https://user-images.githubusercontent.com/75975369/111835528-1f210980-8906-11eb-8844-1cd73538f24a.png)

**Comment by mglknFSD** [comment]
Тут ошибка, этот селектор не работает.

![Screenshot 2021-03-20 at 8 57 20 AM](https://user-images.githubusercontent.com/75975369/111860707-5e794580-895a-11eb-8a74-d6ae15373f73.png)

**Comment by mglknFSD** [comment]
Селекторы по тегам запрещены. Это ограничение БЭМ. И сключение только для html, body и border-box можно задать для всех тегов. 

![Screenshot 2021-03-20 at 9 00 25 AM](https://user-images.githubusercontent.com/75975369/111860826-376f4380-895b-11eb-958a-d0443a89abc8.png)

**Comment by mglknFSD** [comment]
Если мне не изменяет память, плейсхолдеры поддерживаются автопрефиксером.

![Screenshot 2021-03-20 at 9 08 44 AM](https://user-images.githubusercontent.com/75975369/111860987-edd32880-895b-11eb-8e9d-2ee676ea12e0.png)

**Comment by mglknFSD** [comment]
Такие селекторы абсолютно недопустымы. Если структура html поменяется будет сложно это отлаживать.

![Screenshot 2021-03-20 at 9 10 36 AM](https://user-images.githubusercontent.com/75975369/111861037-37bc0e80-895c-11eb-9d0d-453bd2f8a1de.png)

**Comment by mglknFSD** [comment]
[Именование БЭМ сушностей.](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

В этом компоненте еще одна ошибка, ты назначаешь из параметра pug миксина модификатор и расчитываешь что для него найдутся стили. А если кто-то передаст модификатор которого нет в стилях? 

![Screenshot 2021-03-20 at 9 14 38 AM](https://user-images.githubusercontent.com/75975369/111861103-d183bb80-895c-11eb-9cf0-304aa432f3d7.png)

**Comment by mglknFSD** [comment]
[Каждый компонент — отдельный блок из методологии БЭМ.](Каждый компонент — отдельный блок из методологии БЭМ.)

![Screenshot 2021-03-20 at 9 27 04 AM](https://user-images.githubusercontent.com/75975369/111861352-a26e4980-895e-11eb-9a8d-c407c4df1d79.png)

**Comment by igorpichnenko** [comment]
Выше в пункте &:not(first-child) у меня работает этот селектор, на странице color-type он задаёт отступ, без него нет оступа, я проверил

**Comment by mglknFSD** [comment]
> 
> 
> Выше в пункте &:not(first-child) у меня работает этот селектор, на странице color-type он задаёт отступ, без него нет оступа, я проверил

Если тебе не сложно, проверь еще раз, пожалуйста.

**Comment by mglknFSD** [comment]
Я проверил. Ответь на вопрос, пожалуйста. Что, по-твоему, делает этот селектор?

![Screenshot 2021-03-20 at 8 57 20 AM](https://user-images.githubusercontent.com/75975369/111860707-5e794580-895a-11eb-8a74-d6ae15373f73.png)

**Comment by igorpichnenko** [comment]
Добавляет отступ снизу кроме первого элемента

**Comment by mglknFSD** [comment]
> 
> 
> Добавляет отступ снизу кроме первого элемента

Ok. Что такое селектор?

**Comment by igorpichnenko** [comment]
Исправил

**Comment by mglknFSD** [comment]
> 
> 
> Такие селекторы абсолютно недопустымы. Если структура html поменяется будет сложно это отлаживать.
> 
> ![Screenshot 2021-03-20 at 9 10 36 AM](https://user-images.githubusercontent.com/75975369/111861037-37bc0e80-895c-11eb-9d0d-453bd2f8a1de.png)

Этот issue не исправлено в других местах.

**Comment by mglknFSD** [comment]
Именование модификаторов не соответсвует best practice. [Именование БЭМ сушностей.](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![naming](https://user-images.githubusercontent.com/75975369/112726444-953cf600-8f2e-11eb-9f6a-8e56e5a82201.jpg)

**Comment by mglknFSD** [comment]
Лишние свойства. Такого лучше вообще избегать, но в данном случае оно не будет работать.

![props](https://user-images.githubusercontent.com/75975369/112726546-13999800-8f2f-11eb-9f0c-4f2a693509c0.jpg)

Посмотри по всему проекту, пожалуйста. Особое внимание обрати на z-index.

**Comment by mglknFSD** [comment]
> 
> 
> Тут и в других местах необходимо группировать стили внутри селектора где это возможно. Пример для данного случая
> 
> ```css
>   &__input {
> 
>     &::before {
>        ...
>     }
> 
>     &:checked::before {
>        ...
>     }
> 
>     &:checked + #{some_block}__border { // тут используется интерполяция
>        ...
>     }
>   }
> ```
> 
> Удобно когда все стили для класса сгруппированы внутри этого тега и их не надо искать и сложно случайно разделить.
> 
> ![Screenshot 2021-03-19 at 10 54 27 PM](https://user-images.githubusercontent.com/75975369/111835528-1f210980-8906-11eb-8844-1cd73538f24a.png)

Не везде проверено. Посмотри пожалуйста весь проект.

![group](https://user-images.githubusercontent.com/75975369/112726683-c964e680-8f2f-11eb-9b86-781a98a113fc.jpg)

**Comment by igorpichnenko** [comment]
Исправил

**Comment by mglknFSD** [comment]
> 
> 
> > Тут и в других местах необходимо группировать стили внутри селектора где это возможно. Пример для данного случая
> > ```css
> >   &__input {
> > 
> >     &::before {
> >        ...
> >     }
> > 
> >     &:checked::before {
> >        ...
> >     }
> > 
> >     &:checked + #{some_block}__border { // тут используется интерполяция
> >        ...
> >     }
> >   }
> > ```
> > 
> > 
> > Удобно когда все стили для класса сгруппированы внутри этого тега и их не надо искать и сложно случайно разделить.
> > ![Screenshot 2021-03-19 at 10 54 27 PM](https://user-images.githubusercontent.com/75975369/111835528-1f210980-8906-11eb-8844-1cd73538f24a.png)
> 
> Не везде проверено. Посмотри пожалуйста весь проект.
> 
> ![group](https://user-images.githubusercontent.com/75975369/112726683-c964e680-8f2f-11eb-9b86-781a98a113fc.jpg)

Не везде проверено. Посмотри пожалуйста весь проект.
![merge](https://user-images.githubusercontent.com/75975369/113471749-33691880-9467-11eb-8328-7b99d53fd7f1.jpg)

**Comment by mglknFSD** [comment]
> 
> 
> Именование модификаторов не соответсвует best practice. [Именование БЭМ сушностей.](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)
> 
> ![naming](https://user-images.githubusercontent.com/75975369/112726444-953cf600-8f2e-11eb-9f6a-8e56e5a82201.jpg)

Посмотри правила именования модификаторов (ссылка выше) и поправь во всем проекте пожалуйста.

![dat](https://user-images.githubusercontent.com/75975369/113471872-f6e9ec80-9467-11eb-9f4b-b2bd34e91dc9.jpg)

**Comment by mglknFSD** [comment]
Вынеси шрифты в переменную и поправь во всем проекте.

![font](https://user-images.githubusercontent.com/75975369/113471894-27ca2180-9468-11eb-9005-423c80a5af36.jpg)

**Comment by mglknFSD** [comment]
Для подобного модификатора я бы то же использовал правило `with` или использовал пассив `disabled`.

![modificator](https://user-images.githubusercontent.com/75975369/114201616-10ef6780-995f-11eb-9b71-135cecb65001.jpg)

**Comment by mglknFSD** [comment]
Это то же не читается как модификатор. Посмотри по всему проекту пожалуйста.

![mod](https://user-images.githubusercontent.com/75975369/114201844-4e53f500-995f-11eb-9ca1-13c07361a7d1.jpg)

**Comment by mglknFSD** [comment]
Именование модификаторов. Посмотри по всему проекту пожалуйста.

![modificators](https://user-images.githubusercontent.com/75975369/114312151-4ed4c300-9afa-11eb-9e81-ab56a22be7cf.jpg)

**Comment by igorpichnenko** [comment]
https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1
Тут нет примеров как называть модификаторы связанные с позиционированием, такой инфы нет и на официальном сайте, я не знаю как правильно называть вещи, типо если иконка с права находится, icon_right

**Comment by mglknFSD** [comment]
> 
> 
> https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1
> Тут нет примеров как называть модификаторы связанные с позиционированием, такой инфы мало и на официальном сайте, я не знаю как правильно называть вещи, типо если иконка с права находится, icon_right

`Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase.`

**Comment by igorpichnenko** [comment]
Вот я этого и не понимаю, как с позиционированый элемент может отвечать на вопрос "какой", выходит "левый значок" left icon, а если наоборот то icon_left это значок с лева, что отвечает на вопрос "где?". 
Может есть какой-то конкретный пример, модификатора для позиционирования элемента?

**Comment by mglknFSD** [comment]
> 
> 
> Вот я этого и не понимаю, как с позиционированый элемент может отвечать на вопрос "какой", выходит "левый значок" left icon, а если наоборот то icon_left это значок с лева, что отвечает на вопрос "где?".
> Может есть какой-то конкретный пример, модификатора для позиционирования элемента?

Ну я бы следуя рекомендациям назвал _with-left-position

**Comment by igorpichnenko** [comment]
Хорошо, спасибо, подумаю

**Comment by igorpichnenko** [comment]
Раза 4-5 прошёлся по всему проекту, вчитываясь в каждый модификатор, вроде бы я все поправил, можно проверять
