### ISSUE TITLE
Minor remarks

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#4]
1. Тут и в других местах. Грамотность. ([bp](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.26))

![mobile](https://user-images.githubusercontent.com/75975369/109661729-57d98880-7b7b-11eb-8768-4080a3482943.png)

Это пишется как `mobile`. Для VScode есть плагин `Code Spell Checker`.

**Comment by igorpichnenko** [comment]
Я установил плагин, и переименовал все кроме, названий некоторых плагинов..но я когда комментарий писал с непривычки забыл поставить в начале #4 а переименовать нельзя же вроде, и как быть? Следущий комент сделать с пометкой #4 или как

**Comment by mglknFSD** [comment]
![Zerro](https://user-images.githubusercontent.com/75975369/110234619-8a4d0200-7f3c-11eb-9cb6-e44de454ed7e.jpg)

**Comment by mglknFSD** [comment]
Посмотри еще раз, пожалуйста.

`Data` с английского, переводится как данные, а календарная дата - `Date` (`e` на конце), об этом `Code Spell Checker` в VSCode подсказывает.

![data](https://user-images.githubusercontent.com/75975369/111040641-f780fb80-8444-11eb-8154-21ed86573dd8.jpg)

**Comment by mglknFSD** [comment]
Отступы должны быть одинаковыми для всего проекта.

![spaces](https://user-images.githubusercontent.com/75975369/111041362-e5a15780-8448-11eb-8d63-35508d660fa3.jpg)

**Comment by mglknFSD** [comment]
Шрифты, картинки и прочие подключаемые файлы должны хранится в отдельной папке (обычно она называется public или assets).
Исключение составляют картинки использующиеся для декорирования каких-то компонентов (они должны хранится внутри этих компонентов)

![fonts](https://user-images.githubusercontent.com/75975369/111041482-711ae880-8449-11eb-8144-f2abd0291326.jpg)

**Comment by igorpichnenko** [comment]
Настроил stylelint и через него исправил все отступы в scss

**Comment by mglknFSD** [comment]
2 папки с одинаковой семантикой но разными названиями.

![Screenshot 2021-03-19 at 10 35 47 PM](https://user-images.githubusercontent.com/75975369/111833803-bafd4600-8903-11eb-9d77-2d1d664d54b2.png)
