### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#5]
Logo лучше хранить и вставлять svg картинкой. Если лого поменяется, что бы мы могли заменить картинку а не лезть в код.

![logo](https://user-images.githubusercontent.com/75975369/109662685-5e1c3480-7b7c-11eb-9762-9faf92ad6efb.png)

**Comment by igorpichnenko** [comment]
Изменил подключение логотипа, теперь подключаю через svg

**Comment by mglknFSD** [comment]
Svg файлы надо пропустить через svgo
