### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#6]
Не отображается favicon.

![favicon](https://user-images.githubusercontent.com/75975369/109664430-2b733b80-7b7e-11eb-9bda-9242ff89784e.png)

**Comment by igorpichnenko** [comment]
Изменил путь к favicon, была лишняя точка

**Comment by mglknFSD** [comment]
[Favicon для сафари](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#3.3)

**Comment by mglknFSD** [comment]
Svg файлы надо пропустить через [svgo](https://jakearchibald.github.io/svgomg/)

**Comment by igorpichnenko** [comment]
favicon svg я прогнал через svgo 2 раза, но наверное коммент перепутал с svg logo
