### ISSUE TITLE
js

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#7]
1. Вся бизнес логика компонента должна хранится в классах. Причем класс в файле должен быть один. И называться файл должен точно также как класс. Инициализация должна происходить в index.js компонента. [Еще про модульность](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.5)

**Comment by igorpichnenko** [comment]
Получается мне нужно все файлы где используется логика, даже если там пару строк кода, делать обезательно классом?

**Comment by mglknFSD** [comment]
> 
> 
> Получается мне нужно все файлы где используется логика, даже если там пару строк кода, делать обезательно классом?

Да.

**Comment by mglknFSD** [comment]
2. Тут и в других местах. [Именование обработчиков событий.](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#3.3)

![event](https://user-images.githubusercontent.com/75975369/109668228-054f9a80-7b82-11eb-97f7-be175cce9bb1.png)

**Comment by mglknFSD** [comment]
3. Классы которые мы используем доступа из js должны иметь префикс `js-`. Посмотри по всему коду.

![js](https://user-images.githubusercontent.com/75975369/109668601-5fe8f680-7b82-11eb-9651-b754ca9f2ed6.png)

**Comment by mglknFSD** [comment]
Именование файлов. 

![init](https://user-images.githubusercontent.com/75975369/110234255-6dafca80-7f3a-11eb-8488-89b0be07b0df.jpg)

Допустимо `checkbox-list.ts`, так же допустимо `index.ts`.

**Comment by mglknFSD** [comment]
calendar.ts - нет класса.

![init](https://user-images.githubusercontent.com/75975369/110234323-edd63000-7f3a-11eb-8d9f-de7a8b8c20ab.jpg)

**Comment by mglknFSD** [comment]
[ Все проверки содержащие более одного условия должны быть вынесены.](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.9)

![if](https://user-images.githubusercontent.com/75975369/110234573-3f32ef00-7f3c-11eb-9607-63d63120ef17.jpg)

**Comment by mglknFSD** [comment]
Неиспользуемые переменные обычно именуют так `_`

![Screenshot 2021-03-20 at 9 40 22 AM](https://user-images.githubusercontent.com/75975369/111861590-7b187c00-8960-11eb-94bd-23e3f134f190.png)

**Comment by mglknFSD** [comment]
Вот это ты зачем сделал отдельным блоком? Какую проблему это решает? Поясни.

![js](https://user-images.githubusercontent.com/75975369/112726926-e3eb8f80-8f30-11eb-9879-94709cb02dae.jpg)
