### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [igorpichnenko/project#8]
1. Хардкод и модульность. Тут и в похожих местах.

![hardcode](https://user-images.githubusercontent.com/75975369/109670137-dd613680-7b83-11eb-952a-e71cf0a2d794.png)

Компоненты должны быть модульными и функциональными. Если у меня есть list-checkbox, то я ожидаю, что я в него могу бросить конфик в виде массива каких то items с именами checkbox, и он мне их нарисует. То же самое с другими похожими компонентами, а у тебя все это захардкожено, и если я захочу это изменить, то мне придется лезть в код.

**Comment by mglknFSD** [comment]
2. Длинные строки, уходящие за горизонт, которые неудобно читать. Необходимо порефакторить.

![long string](https://user-images.githubusercontent.com/75975369/109671683-59a84980-7b85-11eb-8c31-0221551db4cf.png)

**Comment by mglknFSD** [comment]
3. Кавычки. Для html у нас принято использовать двойные кавычки `"`. Везде в pug я предлагаю использовать их а не смешивать и те и другие. (но в местах использования js внутри pug используй одинарные)
![ggg](https://user-images.githubusercontent.com/75975369/109672370-02ef3f80-7b86-11eb-86ba-ee5d38280cf8.png)

**Comment by igorpichnenko** [comment]
Заменил все одинарные ковычки на двойные в pug файлах, отрефакторил длинные строчки, изменил  миксин чекбокс лист, теперь можно использовать разные конфиги
![Screenshot_2021-03-03-22-29-36-127_com foxdebug acode](https://user-images.githubusercontent.com/76178315/109840514-66ef3200-7c72-11eb-804a-48539ee1c8ee.jpg)
![Uploading Screenshot_2021-03-03-22-31-35-650_com.foxdebug.acode.jpg…]()

**Comment by mglknFSD** [comment]
4. Тут и в других местах посмотри. Везде где возможно необходимо использовать destructuring. 

![destructuring](https://user-images.githubusercontent.com/75975369/110234706-06dfe080-7f3d-11eb-956f-c9ab0a4e5b19.jpg)

**Comment by mglknFSD** [comment]
Хардкод и модульность. Тут и в похожих местах.

 Pie chart компонент подразумевает получение данных извне в виде количества разных голосов. Сейчас этот компонент не функционален.

**Comment by igorpichnenko** [comment]
Изменил компонент pie, теперь в init js есть конфигурация, где можно задавать разное количество голосов и график будет отрисовываться исходя из этих данных

**Comment by mglknFSD** [comment]
Тут не очень понятна логика значение по умолчанию. Если я ничего не передам в этот миксин, он попытается из пустой мапы извлечь данные и отрисует битые картинки?
И если мы отображаем несколько однотипных объектов не логичнее передать массив и нарисовать в цикле?

![Screenshot 2021-03-20 at 9 33 25 AM](https://user-images.githubusercontent.com/75975369/111861472-84551900-895f-11eb-8983-acb54c7264ca.png)

**Comment by mglknFSD** [comment]
Не семантическое именование. Я не могу понять что это за классы, какую смысловую нагрузку они несут.

![pug](https://user-images.githubusercontent.com/75975369/112726136-e5b35400-8f2c-11eb-92f8-689f07110df5.jpg)

**Comment by mglknFSD** [comment]
Очень большой блок. Такое очень сложно поддерживать. Его нужно распилить. И он не один такой.

![block](https://user-images.githubusercontent.com/75975369/112726271-8d308680-8f2d-11eb-9578-a8ab448934c6.jpg)

**Comment by mglknFSD** [comment]
Это не совсем придирка, скорее пожелание. Определись со стилем, и соблюдай его, что бы код выглядел единообразно и его легче было читать. Тут столько пустых строчек, там столько... так не годится. Это касается и css - встречаются плохо форматированный код.

![pug](https://user-images.githubusercontent.com/75975369/112726999-52c8e880-8f31-11eb-9994-a5e61b8cd6e3.jpg)

**Comment by mglknFSD** [comment]
Все ссылки с target="_blank" должны так же содержать атрибут rel="noopener noreferrer". [тык  ](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.16)

**Comment by igorpichnenko** [comment]
Что бы было легче поддерживать распилил на секции, что бы в пределах одного экрана было видно все что относится к секции

**Comment by mglknFSD** [comment]
Еще один очень большой блок который вполне можно распилить на миксины. Так же обрати внимание на очень длинную строку, такое лучше форматировать к более "вертикальному коду"

![pug](https://user-images.githubusercontent.com/75975369/113471329-4fb78600-9464-11eb-8c2b-e414f5f05dc5.jpg)

**Comment by mglknFSD** [comment]
Что за класс .row вне блока? И почему отступы то 1 то 4 если во всем проекте 2? 

![row](https://user-images.githubusercontent.com/75975369/114198617-3333b600-995c-11eb-9e7c-ed9b3d915128.jpg)

**Comment by mglknFSD** [comment]
Очень длинная строка (в мой FullHD монитор она не влезает, и читать такое не удобно), я тебя просил такие стоки отформатировать к вертикальному стилю. 

![long_string](https://user-images.githubusercontent.com/75975369/114199237-c836af00-995c-11eb-9854-e4e3f48b8c6c.jpg)

**Comment by mglknFSD** [comment]
Посмотри по всему проекту пожалуйста.

![string](https://user-images.githubusercontent.com/75975369/114312058-f7365780-9af9-11eb-8723-d806de4eac1c.jpg)

**Comment by igorpichnenko** [comment]
Я эту строку отредактировал до того как отправить вам, и она даже до редактирования у меня помещалась на экране в vs-code на моём ноуте 15 дюйм full hd, может вы используете увеличенный шрифт?  Так как я у себя не вижу проблемы то я и не могу найти по проекту где есть эта проблема, посчитайте сколько у вас букв помещается на экране в строке и добавьте к ТЗ к проекту и я без проблем всюду отредактирую..

**Comment by igorpichnenko** [comment]
![screen](https://user-images.githubusercontent.com/76178315/114494843-0812c600-9beb-11eb-8854-7b0f66156972.jpg)

**Comment by mglknFSD** [comment]
> 
> 
> Я эту строку отредактировал до того как отправить вам, и она даже до редактирования у меня помещалась на экране в vs-code на моём ноуте 15 дюйм full hd, может вы используете увеличенный шрифт? Так как я у себя не вижу проблемы то я и не могу найти по проекту где есть эта проблема, посчитайте сколько у вас букв помещается на экране в строке и добавьте к ТЗ к проекту и я без проблем всюду отредактирую..

Ну если хотите формализма. По стандарту мы используем стайлгайд aribnb, в котором максимальная длинна строки установлена на 80 симолов (что мне лично кажется большим).

![symbols](https://user-images.githubusercontent.com/75975369/114592412-95a9f080-9c93-11eb-8144-3d06034dc8de.jpg)

Я всего лишь хотел указать на общие принципы форматирования - длинные строки не удобно читать и редактировать. И да, я использую крупный шрифт - мне так удобно.

**Comment by igorpichnenko** [comment]
Да конечно нужна конкретика, я не экстрасенс и не знаю какой шрифт вы используете и нет в ТЗ требование что строка должна быть не более 80 символов, поэтому я наугад редактировал строки не зная понравится это вам или нет, достаточно было 1 раз указать конкретно, а не 3 раза..
Теперь зная конкретно требование я отредактировал  строки + - 80 символов

**Comment by mglknFSD** [comment]
> 
> 
> Да конечно нужна конкретика, я не экстрасенс и не знаю какой шрифт вы используете и нет в ТЗ требование что строка должна быть не более 80 символов, поэтому я наугад редактировал строки не зная понравится это вам или нет, достаточно было 1 раз указать конкретно, а не 3 раза..
> Теперь зная конкретно требование я отредактировал строки + - 80 символов

Конечно никто не ожидает, что вы будете угадывать что мы от вас хотим. Но мы ожидаем, что вы будете задавать вопросы если вам что-то не ясно. Вопросы четкие и конкретные. Это очень важный навык. В данном случае вопрос мог быть следующим - "Какой максимальной длинны может быть строка для pug файлов?". И был бы дан ответ.
